-- Thumbs up/down on chat answers. The vote is the user's opt-in to share this question and
-- answer for quality review; no user id or IP is stored. id is a random UUID generated by the
-- client per answer, so changing a vote updates the same row instead of counting twice.
CREATE TABLE IF NOT EXISTS chat_feedback (
  id TEXT PRIMARY KEY,
  rating SMALLINT NOT NULL CHECK (rating IN (-1, 1)),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  citations JSONB NOT NULL DEFAULT '[]',
  source_refs JSONB NOT NULL DEFAULT '[]',
  lang TEXT,
  mode TEXT,
  llm_model TEXT,
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_feedback_rating_time ON chat_feedback(rating, created_at);
