#!/usr/bin/env python3
"""Create a gitignored .vercel.env file from local env files.

This script copies secret values locally without printing them. The generated
.vercel.env is intended for Vercel's Environment Variables import UI.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [ROOT / "backend/.env", ROOT / "frontend/.env.local", ROOT / "data/.env"]
OUT = ROOT / ".vercel.env"

ORDER = [
    "NEXT_PUBLIC_API_URL",
    "POSTGRES_URL",
    "CORS_ORIGINS",
    "CHAT_PROVIDER",
    "GROQ_API_KEY",
    "GROQ_CHAT_MODEL",
    "GROQ_FALLBACK_MODELS",
    "OPENAI_API_KEY",
    "DEEPGRAM_API_KEY",
    "EMBEDDING_PROVIDER",
    "AUTH_SECRET",
    "EMBED_SECRET",
    "RAG_CACHE_TTL_HOURS",
]

# Values that must hold in production regardless of local dev settings. See VERCEL_DEPLOY.md.
PRODUCTION_DEFAULTS = {
    # Empty means same-origin /api in production.
    "NEXT_PUBLIC_API_URL": "",
    "CORS_ORIGINS": "https://noor-travels-chi.vercel.app",
    "CHAT_PROVIDER": "groq",
    # Query embeddings come from the frontend's /api/embed (384-dim MiniLM, matching the DB column).
    "EMBEDDING_PROVIDER": "xenova",
}


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def main() -> None:
    merged: dict[str, str] = {}
    for source in SOURCES:
        merged.update(read_env(source))
    merged.update(PRODUCTION_DEFAULTS)

    lines = [
        "# Generated by scripts/prepare_vercel_env.py",
        "# This file is gitignored. Import it into Vercel Environment Variables.",
    ]
    for key in ORDER:
        if key in merged:
            lines.append(f"{key}={merged[key]}")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.name} with {len(lines) - 2} variables.")
    missing = [k for k in ("POSTGRES_URL", "GROQ_API_KEY", "DEEPGRAM_API_KEY", "AUTH_SECRET") if not merged.get(k)]
    if missing:
        print("Missing (set these in Vercel too): " + ", ".join(missing))


if __name__ == "__main__":
    main()
