#!/usr/bin/env python3
"""Create a gitignored .vercel.env file from local env files.

This script copies secret values locally without printing them. The generated
.vercel.env is intended for Vercel's Environment Variables import UI.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [ROOT / "backend/.env", ROOT / "frontend/.env.local", ROOT / "data/.env"]
OUT = ROOT / ".vercel.env"

ORDER = [
    "NEXT_PUBLIC_API_URL",
    "OPENAI_API_KEY",
    "DEEPGRAM_API_KEY",
    "POSTGRES_URL",
    "SUPABASE_URL",
    "SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_SECRET_KEY",
    "SUPABASE_JWKS_URL",
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
    "FORCE_SQLITE",
    "CORS_ORIGINS",
    "CHAT_PROVIDER",
    "EMBEDDING_PROVIDER",
    "EMBEDDING_MODEL",
    "EMBEDDING_DIMENSIONS",
    "EMBEDDING_BATCH_SIZE",
    "RAG_MIN_SIMILARITY",
    "RAG_RETRIEVAL_K",
    "RAG_FINAL_K",
    "RAG_CACHE_TTL_HOURS",
    "CHAT_MODEL",
]

PRODUCTION_DEFAULTS = {
    # Empty means same-domain /api rewrites in production.
    "NEXT_PUBLIC_API_URL": "",
    # Vercel production must use hosted Postgres/Supabase, not local SQLite.
    "FORCE_SQLITE": "0",
    "CORS_ORIGINS": "https://noor-travels.vercel.app,http://localhost:3000",
    # Avoid installing/running local ML models in serverless.
    "EMBEDDING_PROVIDER": "openai",
    "EMBEDDING_MODEL": "text-embedding-3-small",
    "EMBEDDING_DIMENSIONS": "1536",
    "CHAT_PROVIDER": "local",
    "CHAT_MODEL": "gpt-4o-mini",
    "RAG_RETRIEVAL_K": "20",
    "RAG_FINAL_K": "5",
    "RAG_CACHE_TTL_HOURS": "168",
}


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def main() -> None:
    merged: dict[str, str] = {}
    for source in SOURCES:
        merged.update(read_env(source))
    merged.update(PRODUCTION_DEFAULTS)

    lines = [
        "# Generated by scripts/prepare_vercel_env.py",
        "# This file is gitignored. Import it into Vercel Environment Variables.",
    ]
    for key in ORDER:
        if key in merged:
            lines.append(f"{key}={merged[key]}")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.name} with {len(lines) - 2} variables.")


if __name__ == "__main__":
    main()
