/**
 * Static metadata for the 114 surahs (Hafs ayah counts) — powers
 * generateMetadata on /quran/[surah], the sitemap, and breadcrumbs
 * without a runtime API call.
 */
export type SurahMeta = {
  number: number;
  /** Transliterated name, e.g. "Al-Fatihah". */
  name: string;
  /** English meaning of the name. */
  english: string;
  ayahs: number;
};

export const SURAHS: SurahMeta[] = [
  { number: 1, name: "Al-Fatihah", english: "The Opening", ayahs: 7 },
  { number: 2, name: "Al-Baqarah", english: "The Cow", ayahs: 286 },
  { number: 3, name: "Aal Imran", english: "The Family of Imran", ayahs: 200 },
  { number: 4, name: "An-Nisa", english: "The Women", ayahs: 176 },
  { number: 5, name: "Al-Ma'idah", english: "The Table Spread", ayahs: 120 },
  { number: 6, name: "Al-An'am", english: "The Cattle", ayahs: 165 },
  { number: 7, name: "Al-A'raf", english: "The Heights", ayahs: 206 },
  { number: 8, name: "Al-Anfal", english: "The Spoils of War", ayahs: 75 },
  { number: 9, name: "At-Tawbah", english: "The Repentance", ayahs: 129 },
  { number: 10, name: "Yunus", english: "Jonah", ayahs: 109 },
  { number: 11, name: "Hud", english: "Hud", ayahs: 123 },
  { number: 12, name: "Yusuf", english: "Joseph", ayahs: 111 },
  { number: 13, name: "Ar-Ra'd", english: "The Thunder", ayahs: 43 },
  { number: 14, name: "Ibrahim", english: "Abraham", ayahs: 52 },
  { number: 15, name: "Al-Hijr", english: "The Rocky Tract", ayahs: 99 },
  { number: 16, name: "An-Nahl", english: "The Bee", ayahs: 128 },
  { number: 17, name: "Al-Isra", english: "The Night Journey", ayahs: 111 },
  { number: 18, name: "Al-Kahf", english: "The Cave", ayahs: 110 },
  { number: 19, name: "Maryam", english: "Mary", ayahs: 98 },
  { number: 20, name: "Ta-Ha", english: "Ta-Ha", ayahs: 135 },
  { number: 21, name: "Al-Anbiya", english: "The Prophets", ayahs: 112 },
  { number: 22, name: "Al-Hajj", english: "The Pilgrimage", ayahs: 78 },
  { number: 23, name: "Al-Mu'minun", english: "The Believers", ayahs: 118 },
  { number: 24, name: "An-Nur", english: "The Light", ayahs: 64 },
  { number: 25, name: "Al-Furqan", english: "The Criterion", ayahs: 77 },
  { number: 26, name: "Ash-Shu'ara", english: "The Poets", ayahs: 227 },
  { number: 27, name: "An-Naml", english: "The Ant", ayahs: 93 },
  { number: 28, name: "Al-Qasas", english: "The Stories", ayahs: 88 },
  { number: 29, name: "Al-Ankabut", english: "The Spider", ayahs: 69 },
  { number: 30, name: "Ar-Rum", english: "The Romans", ayahs: 60 },
  { number: 31, name: "Luqman", english: "Luqman", ayahs: 34 },
  { number: 32, name: "As-Sajdah", english: "The Prostration", ayahs: 30 },
  { number: 33, name: "Al-Ahzab", english: "The Combined Forces", ayahs: 73 },
  { number: 34, name: "Saba", english: "Sheba", ayahs: 54 },
  { number: 35, name: "Fatir", english: "The Originator", ayahs: 45 },
  { number: 36, name: "Ya-Sin", english: "Ya-Sin", ayahs: 83 },
  { number: 37, name: "As-Saffat", english: "Those Ranged in Ranks", ayahs: 182 },
  { number: 38, name: "Sad", english: "Sad", ayahs: 88 },
  { number: 39, name: "Az-Zumar", english: "The Groups", ayahs: 75 },
  { number: 40, name: "Ghafir", english: "The Forgiver", ayahs: 85 },
  { number: 41, name: "Fussilat", english: "Explained in Detail", ayahs: 54 },
  { number: 42, name: "Ash-Shura", english: "The Consultation", ayahs: 53 },
  { number: 43, name: "Az-Zukhruf", english: "The Gold Adornments", ayahs: 89 },
  { number: 44, name: "Ad-Dukhan", english: "The Smoke", ayahs: 59 },
  { number: 45, name: "Al-Jathiyah", english: "The Kneeling", ayahs: 37 },
  { number: 46, name: "Al-Ahqaf", english: "The Wind-Curved Sandhills", ayahs: 35 },
  { number: 47, name: "Muhammad", english: "Muhammad", ayahs: 38 },
  { number: 48, name: "Al-Fath", english: "The Victory", ayahs: 29 },
  { number: 49, name: "Al-Hujurat", english: "The Rooms", ayahs: 18 },
  { number: 50, name: "Qaf", english: "Qaf", ayahs: 45 },
  { number: 51, name: "Adh-Dhariyat", english: "The Winnowing Winds", ayahs: 60 },
  { number: 52, name: "At-Tur", english: "The Mount", ayahs: 49 },
  { number: 53, name: "An-Najm", english: "The Star", ayahs: 62 },
  { number: 54, name: "Al-Qamar", english: "The Moon", ayahs: 55 },
  { number: 55, name: "Ar-Rahman", english: "The Most Merciful", ayahs: 78 },
  { number: 56, name: "Al-Waqi'ah", english: "The Inevitable", ayahs: 96 },
  { number: 57, name: "Al-Hadid", english: "The Iron", ayahs: 29 },
  { number: 58, name: "Al-Mujadila", english: "The Pleading Woman", ayahs: 22 },
  { number: 59, name: "Al-Hashr", english: "The Exile", ayahs: 24 },
  { number: 60, name: "Al-Mumtahanah", english: "She Who is to be Examined", ayahs: 13 },
  { number: 61, name: "As-Saff", english: "The Ranks", ayahs: 14 },
  { number: 62, name: "Al-Jumu'ah", english: "Friday", ayahs: 11 },
  { number: 63, name: "Al-Munafiqun", english: "The Hypocrites", ayahs: 11 },
  { number: 64, name: "At-Taghabun", english: "Mutual Disillusion", ayahs: 18 },
  { number: 65, name: "At-Talaq", english: "The Divorce", ayahs: 12 },
  { number: 66, name: "At-Tahrim", english: "The Prohibition", ayahs: 12 },
  { number: 67, name: "Al-Mulk", english: "The Sovereignty", ayahs: 30 },
  { number: 68, name: "Al-Qalam", english: "The Pen", ayahs: 52 },
  { number: 69, name: "Al-Haqqah", english: "The Reality", ayahs: 52 },
  { number: 70, name: "Al-Ma'arij", english: "The Ascending Stairways", ayahs: 44 },
  { number: 71, name: "Nuh", english: "Noah", ayahs: 28 },
  { number: 72, name: "Al-Jinn", english: "The Jinn", ayahs: 28 },
  { number: 73, name: "Al-Muzzammil", english: "The Enshrouded One", ayahs: 20 },
  { number: 74, name: "Al-Muddaththir", english: "The Cloaked One", ayahs: 56 },
  { number: 75, name: "Al-Qiyamah", english: "The Resurrection", ayahs: 40 },
  { number: 76, name: "Al-Insan", english: "Man", ayahs: 31 },
  { number: 77, name: "Al-Mursalat", english: "The Emissaries", ayahs: 50 },
  { number: 78, name: "An-Naba", english: "The Tidings", ayahs: 40 },
  { number: 79, name: "An-Nazi'at", english: "Those Who Drag Forth", ayahs: 46 },
  { number: 80, name: "Abasa", english: "He Frowned", ayahs: 42 },
  { number: 81, name: "At-Takwir", english: "The Overthrowing", ayahs: 29 },
  { number: 82, name: "Al-Infitar", english: "The Cleaving", ayahs: 19 },
  { number: 83, name: "Al-Mutaffifin", english: "The Defrauding", ayahs: 36 },
  { number: 84, name: "Al-Inshiqaq", english: "The Sundering", ayahs: 25 },
  { number: 85, name: "Al-Buruj", english: "The Mansions of the Stars", ayahs: 22 },
  { number: 86, name: "At-Tariq", english: "The Nightcomer", ayahs: 17 },
  { number: 87, name: "Al-A'la", english: "The Most High", ayahs: 19 },
  { number: 88, name: "Al-Ghashiyah", english: "The Overwhelming", ayahs: 26 },
  { number: 89, name: "Al-Fajr", english: "The Dawn", ayahs: 30 },
  { number: 90, name: "Al-Balad", english: "The City", ayahs: 20 },
  { number: 91, name: "Ash-Shams", english: "The Sun", ayahs: 15 },
  { number: 92, name: "Al-Layl", english: "The Night", ayahs: 21 },
  { number: 93, name: "Ad-Duha", english: "The Morning Hours", ayahs: 11 },
  { number: 94, name: "Ash-Sharh", english: "The Relief", ayahs: 8 },
  { number: 95, name: "At-Tin", english: "The Fig", ayahs: 8 },
  { number: 96, name: "Al-Alaq", english: "The Clot", ayahs: 19 },
  { number: 97, name: "Al-Qadr", english: "The Power", ayahs: 5 },
  { number: 98, name: "Al-Bayyinah", english: "The Clear Proof", ayahs: 8 },
  { number: 99, name: "Az-Zalzalah", english: "The Earthquake", ayahs: 8 },
  { number: 100, name: "Al-Adiyat", english: "The Courser", ayahs: 11 },
  { number: 101, name: "Al-Qari'ah", english: "The Calamity", ayahs: 11 },
  { number: 102, name: "At-Takathur", english: "The Rivalry in Worldly Increase", ayahs: 8 },
  { number: 103, name: "Al-Asr", english: "The Declining Day", ayahs: 3 },
  { number: 104, name: "Al-Humazah", english: "The Traducer", ayahs: 9 },
  { number: 105, name: "Al-Fil", english: "The Elephant", ayahs: 5 },
  { number: 106, name: "Quraysh", english: "Quraysh", ayahs: 4 },
  { number: 107, name: "Al-Ma'un", english: "The Small Kindnesses", ayahs: 7 },
  { number: 108, name: "Al-Kawthar", english: "The Abundance", ayahs: 3 },
  { number: 109, name: "Al-Kafirun", english: "The Disbelievers", ayahs: 6 },
  { number: 110, name: "An-Nasr", english: "The Divine Support", ayahs: 3 },
  { number: 111, name: "Al-Masad", english: "The Palm Fiber", ayahs: 5 },
  { number: 112, name: "Al-Ikhlas", english: "The Sincerity", ayahs: 4 },
  { number: 113, name: "Al-Falaq", english: "The Daybreak", ayahs: 5 },
  { number: 114, name: "An-Nas", english: "Mankind", ayahs: 6 },
];

export function getSurahMeta(num: number): SurahMeta | undefined {
  return SURAHS[num - 1]?.number === num ? SURAHS[num - 1] : SURAHS.find((s) => s.number === num);
}
